// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Unpooled Neon connection — used by the CLI for migrate/studio/db-push.
    // Runtime queries use the pooled DATABASE_URL via the adapter in lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
